"""add cards and installment fields on transactions

Revision ID: 09aebfa492b8
Revises: 2926d4e5778b
Create Date: 2026-08-07 11:45:37.982652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09aebfa492b8'
down_revision: Union[str, None] = '2926d4e5778b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('closing_day', sa.Integer(), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cards_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('installment_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('installment_total', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('purchase_group_id', sa.String(length=36), nullable=True))
        batch_op.alter_column('account_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_transactions_card_id'), ['card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_purchase_group_id'), ['purchase_group_id'], unique=False)
        batch_op.create_foreign_key('fk_transactions_card_id_cards', 'cards', ['card_id'], ['id'])

    # ### end Alembic commands ###

    # Alembic não detecta CheckConstraint no autogenerate — adicionado à mão:
    # toda transação pertence a uma conta OU a um cartão, nunca os dois.
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_check_constraint(
            'ck_transactions_account_xor_card',
            '(account_id IS NOT NULL) != (card_id IS NOT NULL)',
        )


def downgrade() -> None:
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('ck_transactions_account_xor_card', type_='check')

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_card_id_cards', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transactions_purchase_group_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_card_id'))
        batch_op.alter_column('account_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('purchase_group_id')
        batch_op.drop_column('installment_total')
        batch_op.drop_column('installment_number')
        batch_op.drop_column('card_id')

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cards_user_id'))

    op.drop_table('cards')
    # ### end Alembic commands ###
