"""add cycle closing day to users

Revision ID: 0fcd115d0807
Revises: b53f71ac7c75
Create Date: 2026-08-20 13:06:58.045615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fcd115d0807'
down_revision: Union[str, None] = 'b53f71ac7c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Ajustado à mão: coluna NOT NULL numa tabela que já tem usuários
    # cadastrados (produção) precisa de server_default, senão o ADD COLUMN
    # falha nas linhas existentes. 24 é só um valor inicial sensato — cada
    # usuário ajusta o próprio depois em Perfil.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('cycle_closing_day', sa.Integer(), nullable=False, server_default='24')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cycle_closing_day')

    # ### end Alembic commands ###
